services:
  chihuashki:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./ChiHuashki:/service/ChiHuashki

    command: >
      sh -c "python ChiHuashki/manage.py runserver 0.0.0.0:80"
