# Generated by Django 3.1.4 on 2020-12-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chihuahua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/dog/', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('rewards', models.TextField(verbose_name='Награды')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('teeth', models.CharField(max_length=7, verbose_name='Зубы')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('color', models.TextField(verbose_name='Окрас')),
                ('type_of_wool', models.CharField(max_length=25, verbose_name='Тип шерсти')),
                ('father', models.CharField(max_length=50, verbose_name='Папа')),
                ('mother', models.CharField(max_length=50, verbose_name='Мама')),
                ('pedigree', models.CharField(max_length=50, verbose_name='Родословная')),
                ('pedigree_link', models.TextField(verbose_name='Ссылка на родословную')),
                ('media_links', models.TextField(verbose_name='Ссылки на медиа')),
            ],
            options={
                'verbose_name': 'Чихуахуа',
                'verbose_name_plural': 'Чишки',
            },
        ),
    ]
