# Generated by Django 3.1.3 on 2021-01-09 14:19

from django.db import migrations, models
import django.db.models.deletion
import dynamic_upload_image_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chihuahua',
            name='photo',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', dynamic_upload_image_field.fields.DynamicUploadImageField(blank=True, max_length=255, upload_to='dummy')),
                ('chihuahua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='settings_content.chihuahua')),
            ],
        ),
    ]
