# Generated by Django 3.1.3 on 2021-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chihuahua',
            name='gender',
            field=models.CharField(default='Сука', max_length=20, verbose_name='Пол'),
        ),
    ]
