# Generated by Django 3.1.3 on 2021-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной', max_length=50, verbose_name='Название шаблона')),
                ('title', models.CharField(default='Выбери себе нового друга!', max_length=25, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('inst', models.TextField(verbose_name='Instagram ссылка')),
                ('facebook', models.TextField(verbose_name='FaceBook ссылка')),
                ('header_background', models.ImageField(upload_to='gallery', verbose_name='Фон шапки')),
                ('header_m_background', models.ImageField(default=None, upload_to='gallery', verbose_name='Фон шапки(смартфон)')),
                ('a_us_t_image', models.ImageField(upload_to='gallery', verbose_name='Верхнее изображение')),
                ('a_us_t_paragraph', models.TextField(blank=True, verbose_name='Верхний параграф')),
                ('a_us_b_image', models.ImageField(upload_to='gallery', verbose_name='Нижнее изображение')),
                ('a_us_b_paragraph', models.TextField(blank=True, verbose_name='Нижний параграф')),
            ],
            options={
                'verbose_name': 'Конфигурации',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
