# Generated by Django 3.1.3 on 2021-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(default=None, upload_to='gallery', verbose_name='Верхнее изображение')),
                ('top_paragraph', models.TextField(blank=True, verbose_name='Верхний параграф')),
                ('bottom_image', models.ImageField(default=None, upload_to='gallery', verbose_name='Нижнее изображение')),
                ('bottom_paragraph', models.TextField(blank=True, verbose_name='Нижний параграф')),
            ],
            options={
                'verbose_name': 'Блок "О нас"',
                'verbose_name_plural': 'Блок "О нас"',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, verbose_name='Название картинки')),
                ('image', models.ImageField(default=None, upload_to='gallery', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение для галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
    ]
