# Generated by Django 3.1.4 on 2021-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chihuahua',
            name='reserve',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=20, verbose_name='В резерве'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='face_name',
            field=models.CharField(default='Мой логин FaceBook', max_length=25, verbose_name='FaceBook(Имя)'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='first_phone',
            field=models.CharField(default='+38(0**)-***-**-**', max_length=20, verbose_name='Первый номер телефона'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='footer_title',
            field=models.CharField(default='Заголовок футера', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='inst_name',
            field=models.CharField(default='Мой логин Instagram', max_length=25, verbose_name='Instagram(Имя)'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='second_phone',
            field=models.CharField(default='+38(0**)-***-**-**', max_length=20, verbose_name='Второй номер телефона'),
        ),
        migrations.AlterField(
            model_name='chihuahua',
            name='gender',
            field=models.CharField(choices=[('female', 'сука'), ('male', 'кобель')], default='female', max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='chihuahua',
            name='pedigree_link',
            field=models.URLField(verbose_name='Ссылка на родословную'),
        ),
        migrations.AlterField(
            model_name='chihuahua',
            name='sale',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=20, verbose_name='Для продажи'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='facebook',
            field=models.URLField(verbose_name='FaceBook ссылка'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='inst',
            field=models.URLField(verbose_name='Instagram ссылка'),
        ),
    ]
