# Generated by Django 3.1.3 on 2021-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chihuahua',
            name='reserve',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=20, verbose_name='В резерве'),
        ),
        migrations.AlterField(
            model_name='chihuahua',
            name='sale',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='да', max_length=20, verbose_name='Для продажи'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='facebook',
            field=models.URLField(verbose_name='FaceBook ссылка'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='inst',
            field=models.URLField(verbose_name='Instagram ссылка'),
        ),
    ]
