# Generated by Django 3.1.3 on 2021-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0002_chihuahua_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chihuahua',
            name='gender',
            field=models.CharField(choices=[(1, 'сука'), (2, 'кобель')], default='сука', max_length=20, verbose_name='Пол'),
        ),
    ]
