# Generated by Django 3.1.3 on 2021-01-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0002_auto_20210109_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chihuahua',
            name='media_links',
        ),
    ]
