# Generated by Django 3.1.3 on 2021-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0003_remove_chihuahua_media_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
