# Generated by Django 3.1.3 on 2021-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0003_auto_20210110_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chihuahua',
            name='gender',
            field=models.CharField(choices=[(1, 'сука'), (2, 'кобель')], default=1, max_length=20, verbose_name='Пол'),
        ),
    ]
