# Generated by Django 3.1.3 on 2021-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0003_remove_siteconfigurations_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigurations',
            name='first_viber_flag',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=5, verbose_name='Вайбер'),
        ),
        migrations.AddField(
            model_name='siteconfigurations',
            name='second_viber_flag',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=5, verbose_name='Вайбер'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='face_name',
            field=models.CharField(blank=True, default='Мой логин FaceBook', max_length=25, verbose_name='FaceBook(Имя)'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='first_phone',
            field=models.CharField(blank=True, default='+38(0**)-***-**-**', max_length=20, verbose_name='Первый номер телефона'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='inst_name',
            field=models.CharField(blank=True, default='Мой логин Instagram', max_length=25, verbose_name='Instagram(Имя)'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='second_phone',
            field=models.CharField(blank=True, default='+38(0**)-***-**-**', max_length=20, verbose_name='Второй номер телефона'),
        ),
    ]
