# Generated by Django 3.1.3 on 2021-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0004_auto_20210209_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigurations',
            name='first_viber_flag',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=5, verbose_name='Вайбер'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='second_viber_flag',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=5, verbose_name='Вайбер'),
        ),
    ]
