# Generated by Django 3.1.3 on 2021-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0004_auto_20210109_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='chihuahua',
            name='video',
            field=models.FileField(null=True, upload_to='videos', verbose_name='Видео'),
        ),
    ]
