# Generated by Django 3.1.3 on 2021-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0006_auto_20210110_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='chihuahua',
            name='age',
            field=models.CharField(choices=[('puppy', 'щенок'), ('adult', 'взрослый')], default='adult', max_length=20, verbose_name='Щенок/Взрослый'),
        ),
        migrations.AddField(
            model_name='chihuahua',
            name='sale',
            field=models.CharField(choices=[('yes', 'да'), ('not', 'нет')], default='yes', max_length=20, verbose_name='Для продажи'),
        ),
    ]
