# Generated by Django 3.1.3 on 2021-03-03 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0006_siteconfigurations_rich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigurations',
            name='Rich',
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='a_us_b_paragraph',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Нижний параграф'),
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='a_us_t_paragraph',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Верхний параграф'),
        ),
    ]
