# Generated by Django 3.1.3 on 2021-03-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0007_auto_20210303_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigurations',
            name='header_m_background',
        ),
    ]
