# Generated by Django 3.1.3 on 2021-01-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0007_auto_20210111_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
