# Generated by Django 3.1.3 on 2021-01-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0008_auto_20210111_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, verbose_name='Название картинки')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка на чишку')),
            ],
            options={
                'verbose_name': 'Изображение для галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='GalleryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='settings_content.galleryimage')),
            ],
        ),
    ]
