# Generated by Django 3.1.3 on 2021-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_content', '0009_galleryimage_galleryimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default=None, upload_to='gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='GalleryImg',
        ),
    ]
